"""Generate README tables from the canonical listings JSON."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
import sys

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from scrapers.utils import load_listings

README_PATH = ROOT_DIR / "README.md"


def generate_readme() -> None:
    """Render the README from the canonical JSON dataset."""

    data = load_listings()
    listings = data.get("listings", [])
    uk_placements = [
        item for item in listings if item.get("country") == "UK" and item.get("type") == "industrial_placement"
    ]
    canada_coops = [
        item for item in listings if item.get("country") == "Canada" and item.get("type") == "coop"
    ]

    content = "\n".join(
        [
            "# UK & Canada SWE Industrial Placements and Co-ops",
            "",
            "This repository tracks UK 12-month software engineering industrial placements and Canadian SWE co-ops.",
            "Listings are stored in `data/listings.json` and the tables below are generated by `scripts/generate_readme.py`.",
            "Age is based on the original posting date when available; otherwise the source's relative age text is shown.",
            "The dataset is designed to refresh automatically via GitHub Actions.",
            "",
            "## Folder structure",
            "",
            "- `data/listings.json` — canonical dataset of all roles.",
            "- `scrapers/` — scraper framework, country-specific scrapers, and helpers.",
            "- `scripts/generate_readme.py` — generates the Markdown tables from JSON.",
            "- `.github/workflows/update-listings.yml` — scheduled refresh automation.",
            "",
            "## 🇬🇧 UK Software Engineering Industrial Placements (12 months)",
            "",
            _render_table(uk_placements),
            "",
            "## 🇨🇦 Canada Software Developer Co-ops",
            "",
            _render_table(canada_coops),
            "",
            "## Quick start",
            "",
            "```bash",
            "python -m venv .venv",
            "source .venv/bin/activate  # or .venv\\Scripts\\activate on Windows",
            "pip install -r requirements.txt",
            "python -m scrapers",
            "python scripts/generate_readme.py",
            "```",
            "",
            "## Data model",
            "",
            "Each listing includes fields such as `id`, `company`, `role`, `short_role`, `type`, `category`, `ai_focus`, `duration_months`, `duration_text`, `country`, `city`, `region`, `locations`, `application_url`, `source`, `posted_date`, `posted_age_text`, `last_seen_date`, `open`, `sponsorship`, and `notes`.",
            "",
            "## Automation",
            "",
            "A scheduled GitHub Action refreshes the scrapers and regenerates this README automatically.",
            "",
            "For contribution guidance, see [CONTRIBUTING.md](CONTRIBUTING.md).",
        ]
    )

    README_PATH.write_text(content + "\n", encoding="utf-8")


def _render_table(listings: Iterable[dict]) -> str:
    rows = [
        "| Company | Role | Location | Duration | AI Focus | Application | Age |",
        "|--------|------|----------|----------|----------|-------------|-----|",
    ]
    for listing in listings:
        company = _escape(listing.get("company", ""))
        role = _escape(listing.get("short_role") or listing.get("role", ""))
        location = _escape(_format_location(listing))
        duration = _escape(_format_duration(listing))
        ai_focus = "Yes" if listing.get("ai_focus") else "No"
        application_url = listing.get("application_url", "")
        application = f"[Apply]({application_url})" if application_url else ""
        age = _escape(_format_age(listing))
        rows.append(
            f"| {company} | {role} | {location} | {duration} | {ai_focus} | {application} | {age} |"
        )
    if len(rows) == 2:
        rows.append("| _No listings yet_ | _No listings yet_ | _No listings yet_ | _No listings yet_ | _No listings yet_ | _No listings yet_ | _No listings yet_ |")
    return "\n".join(rows)


def _format_location(listing: dict) -> str:
    parts = [part for part in [listing.get("city"), listing.get("region"), listing.get("country")] if part]
    return ", ".join(parts)


def _format_duration(listing: dict) -> str:
    duration_text = listing.get("duration_text")
    if duration_text:
        return duration_text
    months = listing.get("duration_months")
    return f"{months} months" if months else "Unknown"


def _format_age(listing: dict) -> str:
    date_text = listing.get("posted_date")
    if date_text:
        try:
            date_value = datetime.fromisoformat(date_text)
        except ValueError:
            return "Unknown"
        if date_value.tzinfo is None:
            date_value = date_value.replace(tzinfo=timezone.utc)
        delta_days = max(0, (datetime.now(timezone.utc) - date_value).days)
        if delta_days < 30:
            return f"{delta_days}d"
        if delta_days < 365:
            return f"{round(delta_days / 30)}mo"
        return f"{round(delta_days / 365)}y"

    relative_age = listing.get("posted_age_text")
    if relative_age:
        return relative_age

    return "Unknown"


def _escape(value: str) -> str:
    return value.replace("|", "\\|")


if __name__ == "__main__":
    generate_readme()
